services:
  postgres:
    image: postgres:16-alpine
    container_name: leanshop-db
    environment:
      POSTGRES_USER: lean
      POSTGRES_PASSWORD: lean
      POSTGRES_DB: leanshop
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
